steps:
- name: "gcr.io/cloud-builders/gcloud"
  args: ["app", "deploy"]
  timeout: "1600s"

- name: 'gcr.io/cloud-builders/gcloud'
  id: Clean Up Old Versions
  entrypoint: 'bash'
  args:
    - '-c'
    - |
      versions=$(gcloud app versions list --service "default" --sort-by '~version' --format 'value(VERSION.ID)' --project "${_PROJECT_ID}" | tail -n +11)

      versions=($versions)  # split to array $versions

      for (( i=0; i<${#versions[@]}; i++ ))
      do
        gcloud app versions delete ${versions[$i]} --service "default" --project "${_PROJECT_ID}" --quiet
      done